apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-service.fullname" . }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort | default 50051 }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "user-service.selectorLabels" . | nindent 4 }}
