{{- if .Values.kong.jwt.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt-credential
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    konghq.com/credential: jwt
stringData:
  algorithm: HS256
  key: {{ .Values.kong.jwt.issuerKey | default "trubanb-service" }}
  secret: {{ .Values.kong.jwt.secret | quote }}
{{- end }}
