{{- if .Values.kong.jwt.enabled -}}
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: {{ .Release.Name }}-jwt-issuer
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: kong
username: {{ .Values.kong.jwt.consumerUsername | default "trubanb-jwt-issuer" }}
credentials:
  - {{ .Release.Name }}-jwt-credential
{{- end }}
