{{- if .Values.kong.jwt.enabled -}}
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: trubanb-jwt-issuer
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: kong
username: trubanb-jwt-issuer
{{- end }}
