{{- if .Values.kong.jwt.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: trubanb-jwt-credential
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
    "konghq.com/credential": "jwt"
stringData:
  algorithm: HS256
  key: trubanb-service
  secret: {{ .Values.kong.jwt.secret | quote }}
{{- end }}
